### PR TITLE
Fix Tic Tac Toe example not loading even with the correct path

### PR DESCRIPTION
**Pull request by pharaone**
I noticed that even after the path fix the page still can't be opened because it is not a "GitHub Pages" site.
By using an URL that directs directly to the Tic Tac Toe example file in GitHub we should fix the problem.

I believe this would be the best solution to have it working. Thank you for the documentation!

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Might a relative link work? That or a link to the raw version in the repo?

**Comment by ardonjr** [comment]
I noticed by just using the direct URL the YAML is found:
https://oai.github.io/Documentation/examples/tictactoe.yaml
But not sure if thats acceptable.. for now it might be as the example documentation fails at this point.

**Comment by MikeRalphson** [comment]
We now have the site hosted at https://learn.openapis.org - can you re-check? This PR may no longer be necessary.

**Comment by MikeRalphson** [comment]
Ping @ardonjr

**Comment by lornajane** [comment]
I don't think we need this any more, since moving the site, this PR and the related issue can be closed.

**Pull request closed without merging**
